apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
  - source:
      kind: ConfigMap
      name: example
      fieldPath: data.username
    targets:
      - select:
          kind: Deployment
          name: example
        fieldPaths:
          - spec.template.spec.containers.[name=example].env.[name=USER_NAME].value
  - source:
      kind: Secret
      name: example
      fieldPath: data.password
    targets:
      - select:
          kind: Deployment
          name: example
        fieldPaths:
          - spec.template.spec.containers.[name=example].env.[name=USER_PASSWORD].value
