apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: patch-example
resources:
- deployment.yaml

secretGenerator:
  - name: example
    literals:
      - password=secret

configMapGenerator:
  - name: example
    literals:
      - username=alice
